### ISSUE TITLE
can't build with 4.10.1

### ISSUE THREAD

**Issue by nneesshh** [PaddleCreekGames/Proto3RPC_UE4#1]
g:\ue4\unrealengine-4.10.1-release\engine\source\runtime\online\http\public\HttpModule.h(60): error C3861: 'check': identifier not found

**Comment by NeTTwerk** [comment]
I have a fix in a local client - will get it in today. Sorry about that.

**Comment by NeTTwerk** [comment]
Should be fixed now
